apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-name
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://localhost:5672"
  - name: durable
    value: "true"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
scopes:
  - administration-api
  - veterinarian-api
