apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: animal-subscription
spec:
  topic: animal-created
  routes:
    default: /veterinarian/animal-created
  pubsubname: pubsub
scopes: #burde begrænse adgang til kun at være fra veterinarian og admin
- administration.api
- veterinarian.api
