apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: animal-registration-sub
spec:
  topic: animal-registration
  routes:
    default: /veterinarian/process-registration
  pubsubname: pubsub-name